# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sharemytutoring-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  # ENVIRONMENT: 
  #   Type: String
  #   Default: Prod
  # APIDomainName: 
  #   Type: String
  #   Default: sharemytutoring-com-api-domain-setup

  DATABASEHOST: 
    Type: String
    Default: sharemytutoring.cfw1z3f57fsu.eu-west-2.rds.amazonaws.com

  DATABASEUSER: 
    Type: String
    Default: Admin

  DATABASEPASSWORD:
    Type: String
    Default: Sybase01!

  DATABASENAME: 
    Type: String
    Default: sharemytutoring

  DATABASEPORT:
    Type: String
    Default: 3306

  JWTTUTORSECRET:
    Type: String
    Default: bestTutoringSite

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Runtime: nodejs10.x
    MemorySize: 128
    Timeout: 100
    VpcConfig:
      SecurityGroupIds:
        - sg-00634fc3a409d8b49
      SubnetIds:
        - subnet-0552fc6f5cdaf111d
    Environment:
      Variables:
        DB_HOST: !Ref DATABASEHOST
        DB_USER: !Ref DATABASEUSER
        DB_PASSWORD: !Ref DATABASEPASSWORD
        DB_DATABASE: !Ref DATABASENAME
        DB_PORT: !Ref DATABASEPORT
        JWT_SECRET: !Ref JWTTUTORSECRET

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  #
  # Create the api gateway from a swagger file
  #
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
        Name: sharemytutoring-com
        DefinitionBody:
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location: ./swagger.yml
        EndpointConfiguration: REGIONAL
        StageName: Prod

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn:
      - ApiGateway
    Properties:
      BasePath: "v1"
      DomainName: api.sharemytutoring.com
      RestApiId: !Ref ApiGateway
      Stage: !Ref ApiGateway.Stage

  #
  # Create User Accounts
  #
  userAccountMaintenance:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userAccountMaintenanceTest
      Handler: user-account.userAccountHandler
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the user creation, updating, deleting and retrieval.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user
            Method: ANY

  #
  # User Login
  #
  userLogin:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userLoginTest
      Handler: user-login.userLogin
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the user creation, updating, deleting and retrieval.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user-auth
            Method: ANY

  #
  # User Media Verification
  #
  userMediaVerification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userMediaVerificationTest
      Handler: user-media-verification.validateMedia
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the user creation, updating, deleting and retrieval.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user-media-verify
            Method: ANY

  #
  # User Password reset
  #
  userPasswordReset:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userPasswordResetTest
      Handler: user-password-reset.userPasswordResetHandler
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the reseting and emailing a password reset.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user-password-reset
            Method: ANY

  #
  # User Email Usernames
  #
  userEmailUsernames:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userEmailUsernamesTest
      Handler: user-email-usernames.emailUsernames
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: Emails all the usernames associated to an email address to the specified email address.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user-email-usernames
            Method: ANY

  #
  # User Contact Details
  #
  userContactDetailsMaintenance:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userContactDetailsMaintenanceTest
      Handler: user-contact-details.userContactDetailsHandler
      CodeUri: lambdas/handlers/user
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the tutor creation, updating, deleting and retrieval.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTUserAccountLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /user-contact-details
            Method: ANY

  #
  # Static Data - Subjects
  #
  staticDataSubjects:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: staticDataSubjectsTest
      Handler: subjects.subjectsHandler
      CodeUri: lambdas/handlers/static-data/subjects
      Role: arn:aws:iam::216211142709:role/smt-dev-lambda-execution
      Description: handles the subjects and subjects categories retrieval.
      Layers:
      - !Ref SMTCommonLayer
      - !Ref SMTSubjectsLayer
      Events:
        ApiGateway:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /subjects
            Method: ANY

  SMTCommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: smt-common-test
      Description: Contains the common modules for the functions and our mySQL database handlers.
      ContentUri: layers/common/
      CompatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
      RetentionPolicy: Delete

  SMTUserAccountLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: smt-user-account-test
      Description: Contains the code for the user account functionality and database models.
      ContentUri: layers/user-account/
      CompatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
      RetentionPolicy: Delete

  SMTSubjectsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: smt-static-data-subjects-test
      Description: Contains the code for handling the subjects database model
      ContentUri: layers/static-data/subjects/
      CompatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
      RetentionPolicy: Delete

Outputs:

  APIGatewayID:
    Description: "API Gateway - Gateway ID"
    Value: !Ref ApiGateway

  APIGatewayRootResourceID:
    Description: "API Gateway - Gateway Root Resource ID"
    Value: !GetAtt ApiGateway.RootResourceId
